// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type Channel struct {
	ID          string
	Title       string
	Description string
	Thumbnail   string
}

type Playlist struct {
	ID          string
	Title       string
	Description string
	Timestamp   time.Time
	Owner       string
}

type PlaylistVideo struct {
	Playlistid string
	Videoid    string
	Sortindex  int64
}

type Video struct {
	ID          string
	Title       string
	Description string
	Timestamp   time.Time
	Duration    string
	Owner       string
	Thumbnail   string
}
